name: Docker Compose Deploy
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  docker-compose:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Docker Compose Down
        run: |
         echo "Hello World"
